# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TechLandNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'QBImagePickerController'
  pod 'XCDYouTubeKit'
end