# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TechLandNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'ART',
      'CxxBridge'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'QBImagePickerController'
  pod 'XCDYouTubeKit', '~> 2.5'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'Interactable', :path => '../node_modules/react-native-interactable'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
end
install! 'cocoapods',
         :deterministic_uuids => false